services:

  frontend:
    image: frontend
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - backend
    volumes:
      - ./dataProtectionKeys:/app/dataProtectionKeys  # Persist keys to the host machine 
    

  backend:
    image: backend
    build:
      context: .
      dockerfile: Backend/Dockerfile
    depends_on:
      - pbengine
      - db
    volumes:
      - ./dataProtectionKeys:/app/dataProtectionKeys  # Persist keys to the host machine 
  pbengine:
    image: pbengine
    build:
      context: .
      dockerfile: pbEngine/dockerfile
      
  db:
    image: postgres:latest
    container_name: Postgres_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: Maagen
      POSTGRES_PASSWORD: Maagen
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
    
volumes:
  postgres_data: