services:
  pb-framework:
    image: pb-framework
    build:
      context: .
      dockerfile: PB-Framework/Dockerfile

  frontend:
    image: frontend
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - backend
    volumes:
      - ./dataProtectionKeys:/app/dataProtectionKeys  # Persist keys to the host machine 

  backend:
    image: backend
    build:
      context: .
      dockerfile: Backend/Dockerfile
    depends_on:
      - pbengine
    volumes:
      - ./dataProtectionKeys:/app/dataProtectionKeys  # Persist keys to the host machine 
  pbengine:
    image: pbengine
    build:
      context: .
      dockerfile: pbEngine/dockerfile