services:

  frontend:
    image: front
    build:
      context: .
      dockerfile: Front/Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - backend 
    

  backend:
    image: backend
    build:
      context: .
      dockerfile: Backend/Dockerfile
    ports:
       - "1234:8080"
    depends_on:
      - pbengine
      - db
      
  pbengine:
    image: pbengine
    build:
      context: .
      dockerfile: pbEngine/dockerfile
      
  db:
    image: postgres:latest
    container_name: Postgres_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: Maagen
      POSTGRES_PASSWORD: Maagen
      POSTGRES_DB: Maagen
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
    
volumes:
  postgres_data:
    driver: local