FROM python:3.9-slim

WORKDIR /app

COPY pbEngine/requirements.txt .
COPY pbEngine/pabutools_functions.py .
COPY pbEngine/main.py .

RUN apt-get update && apt-get install -y \
    build-essential \
    python3-dev \
    libgmp-dev \
    libmpfr-dev \
    libmpc-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

# Expose the port fastapi will run on
EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
