FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
COPY pabutools_functions.py .
COPY main.py .
RUN pip install --upgrade pip
RUN ls -lah && cat requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

# Expose the port fastapi will run on
EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
